/* Drop and recreate tables with data */
DROP TABLE USER_ROLES IF EXISTS
DROP TABLE USERS IF EXISTS

CREATE TABLE users (
  USER_ID INTEGER NOT NULL,
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  ENABLED TINYINT NOT NULL,
  PRIMARY KEY (USER_ID) 
);


CREATE TABLE user_roles (
  USER_ROLE_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  AUTHORITY VARCHAR(45) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID),
  FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
);

INSERT INTO USERS VALUES(001, 'sam', 'secr3t', 1);

INSERT INTO USER_ROLES VALUES (1, 001, 'ROLE_USER');

--select count(*) from users;